### ISSUE TITLE
Unable to debug js files [v3]

### ISSUE THREAD

**Issue by X-Coder** [ColorlibHQ/AdminLTE#1909]
I tried to test debugging of minified adminlte javascript files in chrome, firefox and vs code for new adminlte v3.

I can see the right folder structure of unminified files in debugger, but the whole sourcemap stuff seems not to work right:
- randomly unable to set breakpoints
- breakpoints get removed
- breakpoints moves to other positions
- it opens file adminlte.min.js in debugger when I set breakpoint for example in build/js/Layout.js
- can't view content of variables

Is the js-minify script command configured the right way in package.json?

**Comment by almasaeed2010** [comment]
Are you adding breakpoints to Layout.js then compiling using `npm run js`? If you don't compile the code, you won't be able to see the changes.

Thanks!

**Comment by X-Coder** [comment]
I didn't change or compiled anything, I just wanted to debug it to see whats happening. So I have set the breakpoints in Layouts.js which was loaded into the debugger by adminlte.min.js.map I guess.

What would be the right way to get the debugging working?

**Comment by REJack** [comment]
Please test the v3-dev branch it should be fixed, if not i need to check the map generation

**Comment by REJack** [comment]
I'll close this issue, if this error appear again you can reopen it.

**Comment by X-Coder** [comment]
Just did a quick test: it is way better now than before, breakpoints are working and variables can be debugged now, but it is not stepping to the position its supposed to.

```JS
  $('body').removeClass(ClassName.HOLD)   //<--- breakpoint on this line, as soon it breaks here and I hit "Step over next function call" it will NOT jump to the next following line, but...

  // Activate layout height watcher
  this.fixLayoutHeight()
  $(Selector.SIDEBAR)
	.on('collapsed.lte.treeview expanded.lte.treeview collapsed.lte.pushmenu expanded.lte.pushmenu', () => {
	  this.fixLayoutHeight()
	})

  $(window).resize(() => {
	console.log('resized');
	
	this.fixLayoutHeight()
  })

  $('body, html').css('height', 'auto')  //<--- it jumps to here
```

**Comment by REJack** [comment]
Ok, thanks for the info 😄 could you test if the same results come with the PR #2161, I guess rollup generates something wrong.

**Comment by X-Coder** [comment]
I did "npm install" and "npm run production" after checking out the PR. Then I copied over the files in dist/js into my project, but the issue persists.

**Comment by REJack** [comment]
Ok thanks, I will investigate the minify process may I need to update any devDep. 

Could you provide me the steps to reproduce the issue? I’ve never debugged JS in browsers :/

**Comment by X-Coder** [comment]
Ok, I just found the answer: https://github.com/mishoo/UglifyJS2/issues/2213#issuecomment-313664777
The issue is related to uglifyjs --compress parameter. If I remove it, the stepping is working. But it will increase the file size by 5kb.

Debugging js in browsers is easy:
1. visit the page you want to debug
1. hit F12 or open devtools window
1. open the file you want to debug on the left side in the tree view of "Sources" tab
For minified files, if source map is available, for example in adminlte, you can open the unminified file build/js/Layout.js
1. Place a breakpoint by clicking on the line number
1. reload the page by pressing F5, or do some action on the page so the line, you did set the breakpoint on, is run, then the browser will stop on this line and you can start debugging.
1. For example use the single line step buttons ("step over...", "step into...") on top right, view variables on right or use console to run js code, eval stuff etc.

**Comment by Zanoshky** [comment]
Starting point 
https://www.google.com/amp/s/scotch.io/tutorials/debug-javascript-in-production-with-source-maps/amp

Never done myself too. Need to do more research

**Comment by REJack** [comment]
@X-Coder oh dang js debugging is such easy 🤦‍♂ I've never needed it till now.

We should move from uglifyjs to terser like bootstrap does.

**Comment by REJack** [comment]
I've replaced uglifyjs with terser in my PR, the min sourcemap is different after running `npm run production`, I hope it works 😄

**Comment by X-Coder** [comment]
Thank you, didn't know terser until now. But still with terser I had to remove "--compress typeofs=false" for me = 4kb increase in file size. I guess source maps don't work in general when compression is turned on.

**Comment by REJack** [comment]
@X-Coder I've test the single line stepping with the terser compressed file and it jumps correctly like it should, but on the [dev demo page](https://adminlte.io/themes/dev/AdminLTE/) it jumps to far like you described.

**Comment by REJack** [comment]
I'll close this issue for now, if this still appear with the next releaes please feel free to open a new issue.
